// <auto-generated />
using System;
using Juhyna_DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Juhyna_DAL.Migrations
{
    [DbContext(typeof(JuhinaDBContext))]
    [Migration("20251110000510_kq2")]
    partial class kq2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Juhyna_DAL.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID")
                        .HasName("PK__Admins__3214EC276047691C");

                    b.HasIndex("PersonID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Adminstrative", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("InventoryID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID")
                        .HasName("PK__Manageme__3214EC27F177E150");

                    b.HasIndex(new[] { "InventoryID" }, "IX_Adminstratives_InventoryID");

                    b.HasIndex(new[] { "PersonID" }, "IX_Adminstratives_PersonID");

                    b.ToTable("Adminstratives");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID")
                        .HasName("PK__Categori__3214EC279D3820BB");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK__Customer__3214EC275F480606");

                    b.HasIndex("PersonID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.CustomerPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("PlaceID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CustomerID" }, "IX_CustomerPlaces_CustomerID");

                    b.HasIndex(new[] { "PlaceID" }, "IX_CustomerPlaces_PlaceID");

                    b.ToTable("CustomerPlaces");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.FillProductinInventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("CreateAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedbyAdminstrativeID")
                        .HasColumnType("int");

                    b.Property<int>("FillQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductInventoryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "CreatedbyAdminstrativeID" }, "IX_FillProductinInventory_CreatedbyAdminstrativeID");

                    b.HasIndex(new[] { "ProductInventoryID" }, "IX_FillProductinInventory_ProductInventoryID");

                    b.ToTable("FillProductinInventory", (string)null);
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Inventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID")
                        .HasName("PK__Inventor__3214EC27299FDBA9");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.InvoicebetweenSaleAdminstrative", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Bought")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("CraeteAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedByAdminstrativeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("ProductinInventoryID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Rest")
                        .HasColumnType("int");

                    b.Property<int>("SaleID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK_FollowingSaleManager_1");

                    b.HasIndex(new[] { "CreatedByAdminstrativeID" }, "IX_InvoicebetweenSaleAdminstrative_CreatedByAdminstrativeID");

                    b.HasIndex(new[] { "ProductinInventoryID" }, "IX_InvoicebetweenSaleAdminstrative_ProductinInventoryID");

                    b.HasIndex(new[] { "SaleID" }, "IX_InvoicebetweenSaleAdminstrative_SaleID");

                    b.ToTable("InvoicebetweenSaleAdminstrative", (string)null);
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBySaleID")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodID")
                        .HasColumnType("int");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<int>("VisitID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "CreatedBySaleID" }, "IX_Orders_CreatedBySaleID");

                    b.HasIndex(new[] { "InvoiceID" }, "IX_Orders_InvoiceID");

                    b.HasIndex(new[] { "PaymentMethodID" }, "IX_Orders_PaymentMethodID");

                    b.HasIndex(new[] { "VisitID" }, "IX_Orders_VisitID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.PaymentMethodBLL", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("PaymentMethod1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PaymentMethod");

                    b.HasKey("ID")
                        .HasName("PK__PaymentM__3214EC2734D6D91C");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int")
                        .HasComment("male:1////female:2");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID")
                        .HasName("PK__People__3214EC27C13865E5");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID")
                        .HasName("PK__Products__3214EC2754882793");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.ProductInventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Bought")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryID")
                        .HasColumnType("int");

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityTotal")
                        .HasColumnType("int");

                    b.Property<int?>("Rest")
                        .HasColumnType("int");

                    b.Property<int>("WaitingQuantity")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK__ProductI__3214EC27E4A6FDE7");

                    b.HasIndex("InventoryID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductInventories");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Return", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdminstrativeID")
                        .HasColumnType("int");

                    b.Property<int>("Back")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("CreateAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBySaleID")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "AdminstrativeID" }, "IX_Returns_AdminstrativeID");

                    b.HasIndex(new[] { "CreatedBySaleID" }, "IX_Returns_CreatedBySaleID");

                    b.HasIndex(new[] { "InvoiceID" }, "IX_Returns_FollowingSaleManagerID");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Sale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CreatedByAdminID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID")
                        .HasName("PK__Sales__3214EC273A8B5EA3");

                    b.HasIndex("CreatedByAdminID");

                    b.HasIndex("PersonID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.SalesCustomer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int?>("SaleID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK__SalesCus__3214EC27C3503000");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SaleID");

                    b.ToTable("SalesCustomers");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.TokenAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<bool>("IsLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RefreshExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaltAccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaltRefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminID");

                    b.ToTable("TokenAdmins");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.TokenAdminstrative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminstrativeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RefreshExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaltAccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaltRefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminstrativeID");

                    b.ToTable("TokenAdminstratives");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.TokenSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RefreshExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SaleID")
                        .HasColumnType("int");

                    b.Property<string>("SaltAccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaltRefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SaleID");

                    b.ToTable("TokenSales");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Visit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBySaleID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("PlaceID")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasComment("Uninterest=1,Done=2");

                    b.HasKey("ID")
                        .HasName("PK__Visits__3214EC2742DA9693");

                    b.HasIndex("CreatedBySaleID");

                    b.HasIndex("CustomerID");

                    b.HasIndex(new[] { "PlaceID" }, "IX_Visits_PlaceID");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Admin", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Person", "Person")
                        .WithMany("Admins")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK__Admins__PersonID__151B244E");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Adminstrative", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Inventory", "Inventory")
                        .WithMany("Adminstratives")
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.Person", "Person")
                        .WithMany("Adminstratives")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK__Managemen__Perso__44FF419A");

                    b.Navigation("Inventory");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Customer", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Person", "Person")
                        .WithMany("Customers")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK__Customers__Perso__5535A963");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.CustomerPlace", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Customer", "Customer")
                        .WithMany("CustomerPlaces")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.Place", "Place")
                        .WithMany("CustomerPlaces")
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.FillProductinInventory", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Adminstrative", "Adminstrative")
                        .WithMany("FillProductinInventories")
                        .HasForeignKey("CreatedbyAdminstrativeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.ProductInventory", "ProductInventory")
                        .WithMany("FillProductinInventories")
                        .HasForeignKey("ProductInventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adminstrative");

                    b.Navigation("ProductInventory");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.InvoicebetweenSaleAdminstrative", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Adminstrative", "CreatedByAdminstrative")
                        .WithMany("InvoicebetweenSaleAdminstratives")
                        .HasForeignKey("CreatedByAdminstrativeID")
                        .IsRequired()
                        .HasConstraintName("FK_FollowingSaleManager_Managements");

                    b.HasOne("Juhyna_DAL.Models.ProductInventory", "ProductinInventory")
                        .WithMany("InvoicebetweenSaleAdminstratives")
                        .HasForeignKey("ProductinInventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.Sale", "Sale")
                        .WithMany("InvoicebetweenSaleAdminstratives")
                        .HasForeignKey("SaleID")
                        .IsRequired()
                        .HasConstraintName("FK_FollowingSaleManager_Sales");

                    b.Navigation("CreatedByAdminstrative");

                    b.Navigation("ProductinInventory");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Order", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Sale", "CreatedBySale")
                        .WithMany("Orders")
                        .HasForeignKey("CreatedBySaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.InvoicebetweenSaleAdminstrative", "Invoice")
                        .WithMany("Orders")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.PaymentMethodBLL", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.Visit", "Visit")
                        .WithMany("Orders")
                        .HasForeignKey("VisitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBySale");

                    b.Navigation("Invoice");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Product", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .HasConstraintName("FK__Products__Catego__3C69FB99");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.ProductInventory", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Inventory", "Inventory")
                        .WithMany("ProductInventories")
                        .HasForeignKey("InventoryID")
                        .HasConstraintName("FK__ProductIn__Inven__3F466844");

                    b.HasOne("Juhyna_DAL.Models.Product", "Product")
                        .WithMany("ProductInventories")
                        .HasForeignKey("ProductID")
                        .HasConstraintName("FK__ProductIn__Produ__403A8C7D");

                    b.Navigation("Inventory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Return", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Adminstrative", "Adminstrative")
                        .WithMany("Returns")
                        .HasForeignKey("AdminstrativeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.Sale", "CreatedBySale")
                        .WithMany("Returns")
                        .HasForeignKey("CreatedBySaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.InvoicebetweenSaleAdminstrative", "Invoice")
                        .WithMany("Returns")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adminstrative");

                    b.Navigation("CreatedBySale");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Sale", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Admin", "CreatedByAdmin")
                        .WithMany("Sales")
                        .HasForeignKey("CreatedByAdminID")
                        .HasConstraintName("FK_Sales_Admins");

                    b.HasOne("Juhyna_DAL.Models.Person", "Person")
                        .WithMany("Sales")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK__Sales__PersonID__5165187F");

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.SalesCustomer", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Customer", "Customer")
                        .WithMany("SalesCustomers")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juhyna_DAL.Models.Sale", "Sale")
                        .WithMany("SalesCustomers")
                        .HasForeignKey("SaleID")
                        .HasConstraintName("FK__SalesCust__SaleI__59063A47");

                    b.Navigation("Customer");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.TokenAdmin", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Admin", "Admin")
                        .WithMany("TokenAdmins")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.TokenAdminstrative", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Adminstrative", "Adminstrative")
                        .WithMany("TokenAdminstrative")
                        .HasForeignKey("AdminstrativeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adminstrative");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.TokenSale", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Sale", "Sale")
                        .WithMany("TokenSale")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Visit", b =>
                {
                    b.HasOne("Juhyna_DAL.Models.Sale", "CreatedBySale")
                        .WithMany("Visits")
                        .HasForeignKey("CreatedBySaleID")
                        .HasConstraintName("FK__Visits__CreatedB__628FA481");

                    b.HasOne("Juhyna_DAL.Models.Customer", "Customer")
                        .WithMany("Visits")
                        .HasForeignKey("CustomerID")
                        .HasConstraintName("FK__Visits__Customer__6383C8BA");

                    b.HasOne("Juhyna_DAL.Models.Place", "Place")
                        .WithMany("Visits")
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBySale");

                    b.Navigation("Customer");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Admin", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("TokenAdmins");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Adminstrative", b =>
                {
                    b.Navigation("FillProductinInventories");

                    b.Navigation("InvoicebetweenSaleAdminstratives");

                    b.Navigation("Returns");

                    b.Navigation("TokenAdminstrative");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Customer", b =>
                {
                    b.Navigation("CustomerPlaces");

                    b.Navigation("SalesCustomers");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Inventory", b =>
                {
                    b.Navigation("Adminstratives");

                    b.Navigation("ProductInventories");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.InvoicebetweenSaleAdminstrative", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Returns");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.PaymentMethodBLL", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Person", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Adminstratives");

                    b.Navigation("Customers");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Place", b =>
                {
                    b.Navigation("CustomerPlaces");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Product", b =>
                {
                    b.Navigation("ProductInventories");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.ProductInventory", b =>
                {
                    b.Navigation("FillProductinInventories");

                    b.Navigation("InvoicebetweenSaleAdminstratives");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Sale", b =>
                {
                    b.Navigation("InvoicebetweenSaleAdminstratives");

                    b.Navigation("Orders");

                    b.Navigation("Returns");

                    b.Navigation("SalesCustomers");

                    b.Navigation("TokenSale");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Juhyna_DAL.Models.Visit", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
