// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class Admin
{
    public int ID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int? PersonID { get; set; }

    public virtual Person Person { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
    public virtual ICollection<TokenAdmin>TokenAdmins { get; set; } = new List<TokenAdmin>();
}