// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class Adminstrative
{
    public int ID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int? PersonID { get; set; }

    public int InventoryID { get; set; }

    public virtual ICollection<FillProductinInventory> FillProductinInventories { get; set; } = new List<FillProductinInventory>();

    public virtual Inventory Inventory { get; set; }

    public virtual ICollection<InvoicebetweenSaleAdminstrative> InvoicebetweenSaleAdminstratives { get; set; } = new List<InvoicebetweenSaleAdminstrative>();

    public virtual Person Person { get; set; }

    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();
    public virtual ICollection<TokenAdminstrative> TokenAdminstrative { get; set; } = new List<TokenAdminstrative>();
}