// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class CustomerPlace
{
    public int Id { get; set; }

    public int PlaceID { get; set; }

    public int CustomerID { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Place Place { get; set; }
}