// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class Customer
{
    public int ID { get; set; }

    public int? PersonID { get; set; }

    public virtual ICollection<CustomerPlace> CustomerPlaces { get; set; } = new List<CustomerPlace>();

    public virtual Person Person { get; set; }

    public virtual ICollection<SalesCustomer> SalesCustomers { get; set; } = new List<SalesCustomer>();

    public virtual ICollection<Visit> Visits { get; set; } = new List<Visit>();
}