// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class FillProductinInventory
{
    public int ID { get; set; }

    public int ProductInventoryID { get; set; }

    public int CreatedbyAdminstrativeID { get; set; }

    public DateOnly CreateAt { get; set; }

    public int FillQuantity { get; set; }

    public virtual Adminstrative Adminstrative { get; set; }

    public virtual ProductInventory ProductInventory { get; set; }
}