// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class InvoicebetweenSaleAdminstrative
{
    public int ID { get; set; }

    public int ProductinInventoryID { get; set; }

    public DateOnly CraeteAt { get; set; }

    public int Quantity { get; set; }

    public int CreatedByAdminstrativeID { get; set; }

    public int SaleID { get; set; }

    public DateTime ConfirmedAt { get; set; }

    public bool IsConfirmed { get; set; }

    public int Bought { get; set; }

    public int Rest { get; set; }

    public int Status { get; set; }

    public virtual Adminstrative CreatedByAdminstrative { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ProductInventory ProductinInventory { get; set; }

    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();

    public virtual Sale Sale { get; set; }
}