// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Juhyna_DAL.Models;

public partial class JuhinaDBContext : DbContext
{
    public JuhinaDBContext()
    {
    }

    public JuhinaDBContext(DbContextOptions<JuhinaDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Adminstrative> Adminstratives { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerPlace> CustomerPlaces { get; set; }

    public virtual DbSet<FillProductinInventory> FillProductinInventories { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<InvoicebetweenSaleAdminstrative> InvoicebetweenSaleAdminstratives { get; set; }

    public virtual DbSet<Order> Orders { get; set; }
    public virtual DbSet<TokenAdmin> TokenAdmins { get; set; }
    public virtual DbSet<TokenAdminstrative> TokenAdminstratives { get; set; }
    public virtual DbSet<TokenSale> TokenSales { get; set; }

    public virtual DbSet<PaymentMethodBLL> PaymentMethods { get; set; }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<Place> Places { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductInventory> ProductInventories { get; set; }

    public virtual DbSet<Return> Returns { get; set; }

    public virtual DbSet<Sale> Sales { get; set; }

    public virtual DbSet<SalesCustomer> SalesCustomers { get; set; }

    public virtual DbSet<Visit> Visits { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=JuhinaDB;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Admins__3214EC276047691C");

            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Person).WithMany(p => p.Admins)
                .HasForeignKey(d => d.PersonID)
                .HasConstraintName("FK__Admins__PersonID__151B244E");
        });

        modelBuilder.Entity<Adminstrative>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Manageme__3214EC27F177E150");

            entity.HasIndex(e => e.InventoryID, "IX_Adminstratives_InventoryID");

            entity.HasIndex(e => e.PersonID, "IX_Adminstratives_PersonID");

            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Inventory).WithMany(p => p.Adminstratives).HasForeignKey(d => d.InventoryID);

            entity.HasOne(d => d.Person).WithMany(p => p.Adminstratives)
                .HasForeignKey(d => d.PersonID)
                .HasConstraintName("FK__Managemen__Perso__44FF419A");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Categori__3214EC279D3820BB");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Customer__3214EC275F480606");

            entity.HasOne(d => d.Person).WithMany(p => p.Customers)
                .HasForeignKey(d => d.PersonID)
                .HasConstraintName("FK__Customers__Perso__5535A963");
        });

        modelBuilder.Entity<CustomerPlace>(entity =>
        {
            entity.HasIndex(e => e.CustomerID, "IX_CustomerPlaces_CustomerID");

            entity.HasIndex(e => e.PlaceID, "IX_CustomerPlaces_PlaceID");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerPlaces).HasForeignKey(d => d.CustomerID);

            entity.HasOne(d => d.Place).WithMany(p => p.CustomerPlaces).HasForeignKey(d => d.PlaceID);
        });

        modelBuilder.Entity<FillProductinInventory>(entity =>
        {
            entity.ToTable("FillProductinInventory");

            entity.HasIndex(e => e.CreatedbyAdminstrativeID, "IX_FillProductinInventory_CreatedbyAdminstrativeID");

            entity.HasIndex(e => e.ProductInventoryID, "IX_FillProductinInventory_ProductInventoryID");

            entity.HasOne(d => d.Adminstrative).WithMany(p => p.FillProductinInventories).HasForeignKey(d => d.CreatedbyAdminstrativeID);

            entity.HasOne(d => d.ProductInventory).WithMany(p => p.FillProductinInventories).HasForeignKey(d => d.ProductInventoryID);
        });

        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Inventor__3214EC27299FDBA9");

            entity.Property(e => e.Address)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<InvoicebetweenSaleAdminstrative>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_FollowingSaleManager_1");

            entity.ToTable("InvoicebetweenSaleAdminstrative");

            entity.HasIndex(e => e.CreatedByAdminstrativeID, "IX_InvoicebetweenSaleAdminstrative_CreatedByAdminstrativeID");

            entity.HasIndex(e => e.ProductinInventoryID, "IX_InvoicebetweenSaleAdminstrative_ProductinInventoryID");

            entity.HasIndex(e => e.SaleID, "IX_InvoicebetweenSaleAdminstrative_SaleID");

            entity.HasOne(d => d.CreatedByAdminstrative).WithMany(p => p.InvoicebetweenSaleAdminstratives)
                .HasForeignKey(d => d.CreatedByAdminstrativeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FollowingSaleManager_Managements");

            entity.HasOne(d => d.ProductinInventory).WithMany(p => p.InvoicebetweenSaleAdminstratives).HasForeignKey(d => d.ProductinInventoryID);

            entity.HasOne(d => d.Sale).WithMany(p => p.InvoicebetweenSaleAdminstratives)
                .HasForeignKey(d => d.SaleID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FollowingSaleManager_Sales");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasIndex(e => e.CreatedBySaleID, "IX_Orders_CreatedBySaleID");

            entity.HasIndex(e => e.InvoiceID, "IX_Orders_InvoiceID");

            entity.HasIndex(e => e.PaymentMethodID, "IX_Orders_PaymentMethodID");

            entity.HasIndex(e => e.VisitID, "IX_Orders_VisitID");

            entity.HasOne(d => d.CreatedBySale).WithMany(p => p.Orders).HasForeignKey(d => d.CreatedBySaleID);

            entity.HasOne(d => d.Invoice).WithMany(p => p.Orders).HasForeignKey(d => d.InvoiceID);

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.Orders).HasForeignKey(d => d.PaymentMethodID);

            entity.HasOne(d => d.Visit).WithMany(p => p.Orders).HasForeignKey(d => d.VisitID);
        });

        modelBuilder.Entity<PaymentMethodBLL>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__PaymentM__3214EC2734D6D91C");

            entity.Property(e => e.PaymentMethod1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PaymentMethod");
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__People__3214EC27C13865E5");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Gender).HasComment("male:1////female:2");
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Salary).HasColumnType("int");
            entity.Property(e => e.SecondName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ThirdName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Place>(entity =>
        {
            entity.Property(e => e.Address).IsRequired();
            entity.Property(e => e.Name).IsRequired();
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Products__3214EC2754882793");

            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Size)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryID)
                .HasConstraintName("FK__Products__Catego__3C69FB99");
        });

        modelBuilder.Entity<ProductInventory>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__ProductI__3214EC27E4A6FDE7");

            entity.HasOne(d => d.Inventory).WithMany(p => p.ProductInventories)
                .HasForeignKey(d => d.InventoryID)
                .HasConstraintName("FK__ProductIn__Inven__3F466844");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductInventories)
                .HasForeignKey(d => d.ProductID)
                .HasConstraintName("FK__ProductIn__Produ__403A8C7D");
        });

        modelBuilder.Entity<Return>(entity =>
        {
            entity.HasIndex(e => e.AdminstrativeID, "IX_Returns_AdminstrativeID");

            entity.HasIndex(e => e.CreatedBySaleID, "IX_Returns_CreatedBySaleID");

            entity.HasIndex(e => e.InvoiceID, "IX_Returns_FollowingSaleManagerID");

            entity.HasOne(d => d.Adminstrative).WithMany(p => p.Returns).HasForeignKey(d => d.AdminstrativeID);

            entity.HasOne(d => d.CreatedBySale).WithMany(p => p.Returns).HasForeignKey(d => d.CreatedBySaleID);

            entity.HasOne(d => d.Invoice).WithMany(p => p.Returns).HasForeignKey(d => d.InvoiceID);
        });

        modelBuilder.Entity<Sale>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Sales__3214EC273A8B5EA3");

            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.CreatedByAdmin).WithMany(p => p.Sales)
                .HasForeignKey(d => d.CreatedByAdminID)
                .HasConstraintName("FK_Sales_Admins");

            entity.HasOne(d => d.Person).WithMany(p => p.Sales)
                .HasForeignKey(d => d.PersonID)
                .HasConstraintName("FK__Sales__PersonID__5165187F");
        });

        modelBuilder.Entity<SalesCustomer>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__SalesCus__3214EC27C3503000");

            entity.HasOne(d => d.Customer).WithMany(p => p.SalesCustomers).HasForeignKey(d => d.CustomerID);

            entity.HasOne(d => d.Sale).WithMany(p => p.SalesCustomers)
                .HasForeignKey(d => d.SaleID)
                .HasConstraintName("FK__SalesCust__SaleI__59063A47");
        });

        modelBuilder.Entity<Visit>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Visits__3214EC2742DA9693");

            entity.HasIndex(e => e.PlaceID, "IX_Visits_PlaceID");

            entity.Property(e => e.CreateAt).HasColumnType("datetime");
            entity.Property(e => e.Status).HasComment("Uninterest=1,Done=2");

            entity.HasOne(d => d.CreatedBySale).WithMany(p => p.Visits)
                .HasForeignKey(d => d.CreatedBySaleID)
                .HasConstraintName("FK__Visits__CreatedB__628FA481");

            entity.HasOne(d => d.Customer).WithMany(p => p.Visits)
                .HasForeignKey(d => d.CustomerID)
                .HasConstraintName("FK__Visits__Customer__6383C8BA");

            entity.HasOne(d => d.Place).WithMany(p => p.Visits).HasForeignKey(d => d.PlaceID);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}