// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public enum enStatusOrder
{
    Completed = 2,
    Canceled = 1,
}
public partial class Order
{
    public int ID { get; set; }

    public int InvoiceID { get; set; }

    public int VisitID { get; set; }

    public int TotalPrice { get; set; }

    public int ProductPrice { get; set; }

    public DateTime CreateAt { get; set; }

    public int PaymentMethodID { get; set; }

    public int Quantity { get; set; }

    public int CreatedBySaleID { get; set; }

    public int Status { get; set; }

    public virtual Sale CreatedBySale { get; set; }

    public virtual InvoicebetweenSaleAdminstrative Invoice { get; set; }

    public virtual PaymentMethodBLL PaymentMethod { get; set; }

    public virtual Visit Visit { get; set; }
}