// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class Person
{
    public int ID { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string ThirdName { get; set; }

    public string LastName { get; set; }

    /// <summary>
    /// male:1////female:2
    /// </summary>
    public int? Gender { get; set; }

    public string Phone { get; set; }

    public int Salary { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Admin> Admins { get; set; } = new List<Admin>();

    public virtual ICollection<Adminstrative> Adminstratives { get; set; } = new List<Adminstrative>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}