// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class Place
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public virtual ICollection<CustomerPlace> CustomerPlaces { get; set; } = new List<CustomerPlace>();

    public virtual ICollection<Visit> Visits { get; set; } = new List<Visit>();
}