// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class Product
{
    public int ID { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public string Size { get; set; }

    public int? CategoryID { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ProductInventory> ProductInventories { get; set; } = new List<ProductInventory>();
}