// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class ProductInventory
{
    public int ID { get; set; }

    public int? QuantityTotal { get; set; }

    public int? Bought { get; set; }

    public int? Rest { get; set; }

    public int? InventoryID { get; set; }

    public int? ProductID { get; set; }

    public int WaitingQuantity { get; set; }

    public int InventoryQuantity { get; set; }

    public virtual ICollection<FillProductinInventory> FillProductinInventories { get; set; } = new List<FillProductinInventory>();

    public virtual Inventory Inventory { get; set; }

    public virtual ICollection<InvoicebetweenSaleAdminstrative> InvoicebetweenSaleAdminstratives { get; set; } = new List<InvoicebetweenSaleAdminstrative>();

    public virtual Product Product { get; set; }
}