// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class Return
{
    public int ID { get; set; }

    public int AdminstrativeID { get; set; }

    public int CreatedBySaleID { get; set; }

    public bool IsConfirmed { get; set; }

    public DateTime ConfirmedAt { get; set; }

    public int Back { get; set; }

    public DateOnly CreateAt { get; set; }

    public int InvoiceID { get; set; }

    public virtual Adminstrative Adminstrative { get; set; }

    public virtual Sale CreatedBySale { get; set; }

    public virtual InvoicebetweenSaleAdminstrative Invoice { get; set; }
}