// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class Sale
{
    public int ID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int? PersonID { get; set; }

    public int? CreatedByAdminID { get; set; }

    public virtual Admin CreatedByAdmin { get; set; }

    public virtual ICollection<InvoicebetweenSaleAdminstrative> InvoicebetweenSaleAdminstratives { get; set; } = new List<InvoicebetweenSaleAdminstrative>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Person Person { get; set; }

    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();

    public virtual ICollection<SalesCustomer> SalesCustomers { get; set; } = new List<SalesCustomer>();

    public virtual ICollection<Visit> Visits { get; set; } = new List<Visit>();
    public virtual ICollection<TokenSale> TokenSale { get; set; } = new List<TokenSale>();

}