// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Juhyna_DAL.Models;

public partial class Visit
{
    public int ID { get; set; }

    public DateTime? CreateAt { get; set; }

    /// <summary>
    /// Uninterest=1,Done=2
    /// </summary>
    public int? Status { get; set; }

    public int? CreatedBySaleID { get; set; }

    public int? CustomerID { get; set; }

    public int PlaceID { get; set; }

    public virtual Sale CreatedBySale { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Place Place { get; set; }
}